CREATE TABLE CATEGORIA (
    id BIGSERIAL PRIMARY KEY,
    nome VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE RECURSO (
    id BIGSERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao TEXT,
    categoria_id BIGINT REFERENCES CATEGORIA(id),
    tipo_recurso VARCHAR(31) NOT NULL
);

CREATE TABLE AUDITORIO (
    recurso_id BIGINT PRIMARY KEY REFERENCES RECURSO(id),
    capacidade INT NOT NULL
);

CREATE TABLE NOTEBOOK (
    recurso_id BIGINT PRIMARY KEY REFERENCES RECURSO(id),
    marca VARCHAR(50),
    modelo VARCHAR(50)
);
